### ISSUE TITLE
TODO done: timers-browserify-full

### ISSUE THREAD

**Issue by jscissr** [jryans/timers-browserify#13]
In [main.js#L13](https://github.com/jryans/timers-browserify/blob/v1.2.0/main.js#L13), there is a comment:

``` js
// TODO: Change to more efficient list approach used in Node.js
// For now, we just implement the APIs using the primitives above.
```

I now built the module [timers-browserify-full](https://github.com/jscissr/timers-browserify-full), basically by taking the node source code of timers and making some changes for browserifying. The size is 1.73KB gzipped (4.45KB uncompressed).

My question is now: What should be done with this? Should browserify use this new module, or is it a better idea to have a light version and an opt-in full version?

[process for browserify](https://www.npmjs.com/package/process) for example says:

> The goal of this module is not to be a full-fledged alternative to the builtin process module.
> [...] We keep this module lean because it will often be included by default[...]

It would be useful to know whether there are modules often used in browserify which `require()` timers, but don't really need the full version.
It is worth noting, that in node the functions `setTimeout`, `clearTimeout`, `setInterval`, `clearInterval`, `setImmediate` and `clearImmediate` are already added to the global namespace.

In [this manual](http://pod.tst.eu/http://cvs.schmorp.de/libev/ev.pod#Be_smart_about_timeouts), referenced in [node](https://github.com/joyent/node/blob/v0.12.0/lib/timers.js#L41), it says about the linked list technique:

> Method # 4 [linked lists] is rather complicated, but extremely efficient, something that really pays off after the first million or so of active timers, i.e. it's usually overkill :)

I don't know if the overhead of this technique has an impact, if only few timers are used. The main use case for linked lists is a server which has many (thousands) of open connections, which all have the same timeout, that is reset for every activity on the wire.

Another issue is that this module (timers-browserify) is not very compatible to node. 
Even though it [says](https://github.com/jryans/timers-browserify/blob/v1.2.0/main.js#L25):

>  our naive impl doesn't care (correctness is still preserved)

It is actually wrong: `timers.enroll` [should](https://github.com/joyent/node/blob/v0.12.0/lib/timers.js#L153) only _set_ the delay time, and `timers.active` should start/reset the timer.

What do you think of [timers-browserify-full](https://github.com/jscissr/timers-browserify-full), do you have some feedback? What are your thoughts?

---

CC: @substack (owner of browserify)

**Comment by jryans** [comment]
Wow, nice work! :smile:

This is first I've heard of someone looking for a more exact implementation, and as you say, it's a larger library. My first impression is that it's best for someone to opt-in to your version as you've suggested on the [timers-browserify-full][1] repo, instead of using it as the default, due to the larger file size. However, I am happy to be convinced otherwise if there is a clear community desire to use your approach.

[1]: https://github.com/jscissr/timers-browserify-full

> Another issue is that this module (timers-browserify) is not very compatible to node.
> Even though it says:
> 
>     our naive impl doesn't care (correctness is still preserved)
> 
> It is actually wrong: timers.enroll should only set the delay time, and timers.active should start/reset the timer.

It seems that you're right, this version is not quite right. I'd certainly merge the patch to fix this error.

**Comment by jryans** [comment]
I don't believe there's anything planned to do here at the moment. `timers-browserify-full` exists for those who need it.
