### ISSUE TITLE
IE11: Invalid Calling Object

### ISSUE THREAD

**Issue by mattdell** [jryans/timers-browserify#21]
I'm having an issue on IE11 when calling process in timers-browserify I get the error "Invalid Calling Object" in the method `process.nextTick()`.

![screen shot 2016-07-04 at 18 02 49](https://cloud.githubusercontent.com/assets/2536442/16566988/8d88221e-4211-11e6-8ef5-cc9f8abac63c.png)

Would anyone be able to shed some light on this one? It's extremely difficult to debug in IE, but `cachedSetTimeout` and `drainQueue` are both defined.

**Comment by jryans** [comment]
In [2.0.0][1], we removed `process.nextTick` from this module. If you use a more recent version, does that solve the issue?

[1]: https://github.com/jryans/timers-browserify/compare/v1.4.2...v2.0.0

**Comment by jryans** [comment]
No reply in a while here. If this is still an issue, please let me know.
